---
- name: Update system
  apt:
    name: "*"
    state: latest
    update_cache: yes
    autoremove: yes

- name: Install OS packages
  apt:
    name: "{{ packages }}"
    state: present

- name: Set hostname
  hostname:
    name: raspberry

#- name: Disable password login
