---

- name: create admin group
  group:
    name: admins
    state: present

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell:  "{{ item.shell }}"
    groups: "{{ item.groups }}"
    create_home: yes
  loop:
    - { name: 'przemek', groups: 'sudo,admins', shell: '/bin/bash' }

- name: Create a 2048-bit SSH key for user in ~/.ssh/id_rsa
  user:
    name: "{{ item.name }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  loop:
    - { name: 'przemek' }

- name: Update authorized keys
  authorized_key:
    user: przemek
    state: present
    key: "{{ item }}"
  with_file:
    - ./files/id_rsa_przemek.pub

- name: Allow sudo for admins group
  copy:
    content: "%admins ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/admins
    mode: 0600