---
- name: Main playbook 
  hosts: lan
  gather_facts: yes
  become: yes

  pre_tasks:
  - name: check connectivity
    ping:
    
  tasks:
  - import_role:
      name: connectivity
      tasks_from: main.yml
  - import_role:
      name: system_config
      tasks_from: main.yml
  - import_role:
      name: create_user
      tasks_from: main.yml