---
- name: Installation of minikube
  hosts: wifi
  gather_facts: yes
  become: yes

  pre_tasks:
  - name: check connectivity
    ping:

  tasks:
  - import_role:
      name: virtualization_KVM
      tasks_from: main.yml